### PR TITLE
support for binary data color extraction (extract from downloaded image)

### PR DESCRIPTION
**Pull request by nleroy917**
Same motivation and concept as before, with following changes:
- Removed references to URL - abstracted to refer only to binary data,
- squashed to one commit
- changed `test_api.py` to test binary data with locally downloaded image rather than one downloaded during testing

### CODE REVIEW

**Comment by obskyr** [comment]
Perfect! Very very nice! I'll merge this and push it to PYPI when I have a moment. Thank you very much for the contribution! 😊

**Comment by nleroy917** [comment]
No problem! Thanks for reviewing considering it!

**Comment by nleroy917** [comment]
Hey - just checking in on the status of this PR

**Comment by obskyr** [comment]
Oh no, I just realized that this is a breaking change. On Python 2, `str` *is* `bytes`, and paths are often supplied in that type – so this PR may break existing Python 2 code that uses `colorgram.py`. I'm sorry – this can't be added to the API without breaking anything… I'd recommend using `BytesIO` user-side when invoking `colorgram.py`!

**Comment by nleroy917** [comment]
Makes sense - thanks for the consideration

**Pull request merged**
